### ISSUE TITLE
怎么更改网易云账号？

### ISSUE THREAD

**Issue by Jingxu23** [kitUIN/nonebot-plugin-ncm#11]
我找了半天配置在哪里，没找到！

比如说，用grep -r 'ncm_admin_level' *查找所有文件，也没找到配置信息。
想问下怎么手动输入账号和密码，或者重新扫码？

感谢

**Comment by kitUIN** [comment]
在.env文件中配置账密，如果有缓存自动登录想更改其他账号，请删除/db/ncm_cache.json文件
