### ISSUE TITLE
[BUG] Use nonebot.plugin.PluginMetadata instead of define your own one

### ISSUE THREAD

**Issue by XZhouQD** [kitUIN/nonebot-plugin-ncm#16]
Hi, I've just helped on debugging someone's issue and find the use of PluginMetadata is wrong:
Check your [\_\_init\_\_.py:L24](https://github.com/kitUIN/nonebot-plugin-ncm/blob/5911efdc6471fab25fac448704f1adb47b397b1d/nonebot-plugin-ncm/__init__.py#L24C3-L24C3)

You should always use `nonebot.plugin.PluginMetadata` instead of define a new one.

This will cause errors when users are using other help plugins and accessing fields like `extra` with default values assumed in `nonebot.plugin.PluginMetadata` while your defined one does not have. For example, [nonebot-plugin-picmenu](https://github.com/hamo-reid/nonebot_plugin_PicMenu) will always read `extra` field of meta without protection (because this field is always there when using nonebot.plugin.PluginMetadata) and will lead to an error like
```
funcs=_meta_data.extra['menu_data'] if 'menu_data' in _meta_data.extra else None,
AttributeError: 'PluginMetadata' object has no attribute 'extra'
```

**Comment by kitUIN** [comment]
thanks for your help
