### ISSUE TITLE
无法播放vip歌曲

### ISSUE THREAD

**Issue by luosheng520qaq** [kitUIN/nonebot-plugin-ncm#18]
正常加载插件并成功登录黑胶账号 但是点会员歌曲时 播放音乐卡片提示 音乐播放：服务器异常

**Comment by kitUIN** [comment]
日志有显示什么吗?
在我的测试机器人上无法复现该问题

**Comment by luosheng520qaq** [comment]
这个问题存在于使用插件点网易云vip歌曲 并且无报错 消息卡片也正常发出 但是在点击卡片尝试播放时 手机QQ客户端报错

另外还上报另一个希望修复的问题 如果一个nonebot连接多个gocq 就会导致使用下载指令时 提示找不到群聊 （nonebot端报错） 这边优化建议是把get_bot() 修改为get_bots()

**Comment by kitUIN** [comment]
也许是因为客户端版本问题?
隔壁的网易云点歌正常吗?
https://github.com/lgc-NB2Dev/nonebot-plugin-multincm

**Comment by luosheng520qaq** [comment]
这个插件与我原有插件存在冲突  所以没有使用 不过这个问题并无大碍 只是不能点歌而已 希望您能优化一下我提到的第二个问题

**Comment by kitUIN** [comment]
好的,这俩天顺手修了
