### ISSUE TITLE
bug:音乐拉取异常

### ISSUE THREAD

**Issue by LingDong233** [kitUIN/nonebot-plugin-ncm#19]
bug1：私聊无法上传音乐，后台报错
![Snipaste_2023-08-10_13-29-09](https://github.com/kitUIN/nonebot-plugin-ncm/assets/82587944/77fc25a9-9886-41a7-8de2-7fd97a986d37)
bug2：群聊获取音乐只有320kbps，无损无法获取（网易云账号已开通黑胶）
![Snipaste_2023-08-10_13-31-48](https://github.com/kitUIN/nonebot-plugin-ncm/assets/82587944/892e6520-b749-47b7-b03c-2ce929674891)
![Snipaste_2023-08-10_13-32-04](https://github.com/kitUIN/nonebot-plugin-ncm/assets/82587944/fd8135f7-dc60-4a75-89fa-c1eee76699e1)

使用环境：
Vmware 17.0.2 + Ubuntu 22.04.2 LTS Server
Nonebot2.0.1
本插件

**Comment by kitUIN** [comment]
私聊的那个报错看看gocq控制台输出什么,
关于只有320kbps,你可以尝试在env配置文件中`ncm_bitrate` 设置320以上的值
如果还是只要mp3,那就是获取不到flac

**Comment by kitUIN** [comment]
问题一为上游问题
https://github.com/Mrs4s/go-cqhttp/issues/2028
