### ISSUE TITLE
KeyError: 'result'

### ISSUE THREAD

**Issue by krasus1995** [kitUIN/nonebot-plugin-ncm#2]
点歌的时候搜素不了，显示KeyError: 'result'

**Comment by kitUIN** [comment]
有详细截图么

**Comment by krasus1995** [comment]
> 

![1652433824(1)](https://user-images.githubusercontent.com/97447697/168253828-131cc322-ae64-4c90-bbb3-552a4f7fc2ca.png)

**Comment by kitUIN** [comment]
> > 
> 
> ![1652433824(1)](https://user-images.githubusercontent.com/97447697/168253828-131cc322-ae64-4c90-bbb3-552a4f7fc2ca.png)

发送给机器人的指令麻烦也发一下

**Comment by krasus1995** [comment]
> 

就是 点歌+歌名

**Comment by krasus1995** [comment]
> 请尝试升级到`1.3.5`版本 `pip3 install nonebot-plugin-ncm --upgrade -i https://pypi.org/simple`
跟之前还是一样的，是我哪里设置没对吗。。。

**Comment by kitUIN** [comment]
> > 请尝试升级到`1.3.5`版本 `pip3 install nonebot-plugin-ncm --upgrade -i https://pypi.org/simple`
> 跟之前还是一样的，是我哪里设置没对吗。。。

升级1.3.6版本，并且开启Debug模式，看看发送后的debug内容

**Comment by krasus1995** [comment]
> > > 请尝试升级到`1.3.5`版本 `pip3 install nonebot-plugin-ncm --upgrade -i https://pypi.org/simple`
> > > 跟之前还是一样的，是我哪里设置没对吗。。。
> 
> 请保证你的依赖pyncm为最新版 `pip3 install pyncm --upgrade -i https://pypi.org/simple` 并开启Debug模式，看看发送后的debug内容

![image](https://user-images.githubusercontent.com/97447697/168530670-234b609a-6c63-43f9-8492-9ea1129a27ba.png)

**Comment by kitUIN** [comment]
预计已被解决,请升级
