### ISSUE TITLE
LLonebot无法发出json消息

### ISSUE THREAD

**Issue by 502milk** [kitUIN/nonebot-plugin-ncm#25]
llonebot那边json卡片需要签名才能发出

**Comment by kitUIN** [comment]
https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/issues/21
隔壁一样的问题，可以看隔壁

**Comment by 502milk** [comment]
> [lgc-NB2Dev/nonebot-plugin-multincm#21](https://github.com/lgc-NB2Dev/nonebot-plugin-multincm/issues/21) 隔壁一样的问题，可以看隔壁

再[3.17.0](https://github.com/LLOneBot/LLOneBot/releases/tag/v3.17.0)版本就支持发送json了，但是要自己签名，也没有给方法XD

**Comment by 502milk** [comment]
https://xiaoapi.cn/?action=doc&id=61
找到一个json签名的~~能否逝一逝~~
