### ISSUE TITLE
点歌报错

### ISSUE THREAD

**Issue by Suercx** [kitUIN/nonebot-plugin-ncm#26]
led', retcode=1200, data=None, message='Error: 音乐消息签名地址未配置\n    at Object.mKgvY (/root/NapCat.linux.x64/napcat.cjs:10049:10457)\n    at genMusicElement (/root/NapCat.linux.x64/napcat.cjs:10049:10815)\n    at createSendElements (/root/NapCat.linux.x64/napcat.cjs:10049:23495)\n    at Object.hFIHr (/root/NapCat.linux.x64/napcat.cjs:10049:27619)\n    at SendMsg._handle (/root/NapCat.linux.x64/napcat.cjs:10049:31805)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SendMsg.websocketHandle (/root/NapCat.linux.x64/napcat.cjs:10043:6389)\n    at async ReverseWebsocket.onmessage (/root/NapCat.linux.x64/napcat.cjs:10662:7382)\n    at async WebSocket.<anonymous> (/root/NapCat.linux.x64/napcat.cjs:10662:10844)', wording='Error: 音乐消息签名地址未配置\n    at Object.mKgvY (/root/NapCat.linux.x64/napcat.cjs:10049:10457)\n    at genMusicElement (/root/NapCat.linux.x64/napcat.cjs:10049:10815)\n    at createSendElements (/root/NapCat.linux.x64/napcat.cjs:10049:23495)\n    at Object.hFIHr (/root/NapCat.linux.x64/napcat.cjs:10049:27619)\n    at SendMsg._handle (/root/NapCat.linux.x64/napcat.cjs:10049:31805)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SendMsg.websocketHandle (/root/NapCat.linux.x64/napcat.cjs:10043:6389)\n    at async ReverseWebsocket.onmessage (/root/NapCat.linux.x64/napcat.cjs:10662:7382)\n    at async WebSocket.<anonymous> (/root/NapCat.linux.x64/napcat.cjs:10662:10844)', echo='4')

**Comment by kitUIN** [comment]
与#25是同一个问题
