### ISSUE TITLE
萌新求助

### ISSUE THREAD

**Issue by huihuiismywife** [kitUIN/nonebot-plugin-ncm#3]
想问一下
ncm_admin: list = ["owner", "admin"]  # 设置命令权限（非解析下载，仅解析功能开关设置）

whitelist: list = []  # 白名单(一键导入)

这两个具体是要填什么啊？

**Comment by kitUIN** [comment]
在群内,ncm的功能默认是关闭的,
所以要开启的话得在群内先发开启指令/ncm t
如果有大批群聊需要开启的话,通过白名单导入群号
ncm_admin设置说明谁能开启和关闭这个ncm,默认是群主跟管理员

**Comment by huihuiismywife** [comment]
了解了，谢啦!!☆⌒(*＾-゜)v
