### ISSUE TITLE
Subscripted generics cannot be used with class and instance checks

### ISSUE THREAD

**Issue by huihuiismywife** [kitUIN/nonebot-plugin-ncm#4]
如题
![图片](https://user-images.githubusercontent.com/107234845/173172842-2960bf83-1236-432f-9940-3af4d501784a.png)

其他功能都能正常运行，就是不能点歌，只要点歌就出现这个问题，
还有个问题是：如何修改点歌的触发词啊？想改成“我要听+歌名”

**Comment by kitUIN** [comment]
如果改触发词的话
更改[源代码](https://github.com/kitUIN/nonebot-plugin-ncm/blob/master/nonebot-plugin-ncm/__init__.py#L66)

**Comment by kitUIN** [comment]
这个报错的话,是最新的nb跟adapter吗

**Comment by huihuiismywife** [comment]
是最新的=，=

**Comment by huihuiismywife** [comment]
我还下了另一个开源的点歌插件，是不是跟另一个的命令重复导致的呀？

**Comment by kitUIN** [comment]
也许有可能

**Comment by kitUIN** [comment]
这样吧我加一个点歌开关

**Comment by kitUIN** [comment]
你在`.env`文件中添加`ncm_search=False`就可以关闭ncm中的点歌功能了

**Comment by huihuiismywife** [comment]
好的，谢谢大佬

**Comment by kitUIN** [comment]
目前解决办法为退回`beta2`版本
