### ISSUE TITLE
功能不全了

### ISSUE THREAD

**Issue by chilldenpa** [kitUIN/nonebot-plugin-ncm#6]
下了一个新插件以后只能(点歌 歌名） 无法弹出命令窗口，回复（要点什么捏）和下载功能，（好像是网易云无法登录）
哦，我把plugin加了s否则另一插件运行不了
![B$75BJ20EP`M3@`RUBL59KR](https://user-images.githubusercontent.com/116000272/196418422-40ff4ccc-aabb-46a9-b6a6-e2ab1d2360d0.png)
![0(0 L P$39TEZ}T~~53L_)K](https://user-images.githubusercontent.com/116000272/196418547-bd442a66-2ad8-47ee-adb0-6bf61a38b2f8.png)
![S09W87JY1HG(KCW4$(71$ D](https://user-images.githubusercontent.com/116000272/196418647-008157bb-d3af-4715-8048-6cee413e3e49.png)

**Comment by kitUIN** [comment]
家人，你这个甚至没有加载插件呀。

**Comment by chilldenpa** [comment]
确实,现在我bot文件里删了一行nonebot load plugin结果2个插件都能运行了，请问这是什么情况（真没python知识）

**Comment by chilldenpa** [comment]
疑，分享歌单无法解析，单曲可以

**Comment by kitUIN** [comment]
怎么在closed里发.......什么歌单无法解析?麻烦发一下链接谢谢
