### ISSUE TITLE
指令权限有问题

### ISSUE THREAD

**Issue by Reversedeer** [kitUIN/nonebot-plugin-ncm#8]
1.在使用指令/ncm *时，只有管理或者群主可以使用，如果bot主人不是管理或者群主则无法使用（建议添加SUPERUSER权限）
2.使用/ncm f/t 时，并不能关闭下载功能和解析功能，并且指令操作对象是下载功能，并非指令所指的解析（建议把解析和下载命令分开）
3.即使关闭了下载功能，回复此指令后依然会下载并上传歌曲
4.初始化插件后群里默认打开了解析功能qwq
5.白名单似乎不起作用

**Comment by kitUIN** [comment]
测试环境为`1.4.2`版本
- 问题1,重新测试未发现该问题,请确认您的操作是否正确?
- 问题2,解析和下载功能是连在一起的,光解析不下载没有用呀,而且使用/ncm f/t 时，确实关闭了下载功能和解析功能,而且该功能生效在一个群内, `1.5.0`版本中合成一个功能
- 问题3,由于是在开启情况下解析,所以即使关闭,回复语句依旧会下载,`1.5.0`版本修复
- 问题4 在`1.5.0`版本修复
- 问题5 在`1.5.0`版本被废弃

`1.5.0`版本将会简化功能,并且进行`bug`修复,详见Readme文件

**Comment by Reversedeer** [comment]
问题1 我在翻源码发现没有添加[SUPERUSER]固会出现无法/ncm的问题，但是看到作者在1.5.0版本已经优化了QWQ
一次性提出这么多BUG，哈哈哈
